### ISSUE TITLE
Failure to parse dev release: 22:dev

### ISSUE THREAD

**Issue by pierres** [OpenVPN/openvpn3-indicator#12]
The current 22 dev release reports "v22:dev" as version. Therefore the indicator fails with:
```
Traceback (most recent call last):
File "/usr/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 131, in on_startup
ValueError: invalid literal for int() with base 10: '22:dev'
```

**Comment by grzegorz-gutowski** [comment]
Thanks for the report. Obviously, I didn't try the latest version yet.
I have already pushed a patch which handles parsing of the version string a little better.
Fedora and Ubuntu builds should be available shortly.

**Comment by pierres** [comment]
The latest commit works great. Thank you!
