### ISSUE TITLE
Latest update shows toast notification to upgrade openvpn3 version to v22 on startup in ubuntu 22.04

### ISSUE THREAD

**Issue by pushkargogte** [OpenVPN/openvpn3-indicator#13]
After the latest update openvpn3-indicator shows toast notification to upgrade openvpn3 version to v22 on startup in ubuntu 22.04

this toast should be disabled for users on ubuntu 22.04 as openvpn3 v22_dev builds are released only for v24.04 `https://github.com/OpenVPN/openvpn3-linux/issues/171#issuecomment-2181511850` and for users currently on 22.04 won't be able to update to 24.04 until v24.04.1 which is due to release in August as per Ubuntu upgrade policy for LTS users

so for time being it will be best to disable this upgrade toast for ubuntu 22.04

**Comment by grzegorz-gutowski** [comment]
Sorry for that, I accidentally pushed parts of my private development version.
The feature will stay there, but recommend version at least 21, not 22.
