### ISSUE TITLE
Fails to start with 0.1.20240705192959-noble

### ISSUE THREAD

**Issue by choseh** [OpenVPN/openvpn3-indicator#18]
Error I'm getting is:

Traceback (most recent call last):
  File "/usr/local/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 131, in on_startup
ValueError: invalid literal for int() with base 10: '22:dev'

Works fine from source btw.

**Comment by choseh** [comment]
just noticed the version detection has already been fixed ~2 weeks ago, so it's basically not an issue anymore

**Comment by choseh** [comment]
Reopening to ask when the fixed version will make it to the ppa :)

**Comment by grzegorz-gutowski** [comment]
All the changes are in the ppa. They get there automatically with each commit.

**Comment by choseh** [comment]
mh then it's actually broken in the current version:

`apt policy openvpn3-indicator
openvpn3-indicator:
  Installed: 0.1.20240705192959-noble
  Candidate: 0.1.20240705192959-noble
  Version table:
 *** 0.1.20240705192959-noble 500
        500 https://ppa.launchpadcontent.net/grzegorz-gutowski/openvpn3-indicator/ubuntu noble/main amd64 Packages
        500 https://ppa.launchpadcontent.net/grzegorz-gutowski/openvpn3-indicator/ubuntu noble/main i386 Packages
        100 /var/lib/dpkg/status
`

`openvpn3-indicator 
Traceback (most recent call last):
  File "/usr/local/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 131, in on_startup
ValueError: invalid literal for int() with base 10: '22:dev'`

`which openvpn3-indicator 
/usr/local/bin/openvpn3-indicator`

**Comment by choseh** [comment]
my bad, probably from a very early installation. thanks :)
