### ISSUE TITLE
Change in status icon for a Paused connection (humble enhancement request)

### ISSUE THREAD

**Issue by sgrzy01** [OpenVPN/openvpn3-indicator#20]
So... many of the applications I use require authentication from our corporate networks, which require me to be connected via OpenVPN.

But after authentication, sometimes I want the speed of my local connection (no split-tunnel) , so I pause the connection, un-pause when I need corporate resources or authentication.

How bout a change in the icon when paused?  Perhaps just change the orange part of the OpenVPN logo to yellow? A quick glance at the icon would be great to know my connection status.

Thanks!.

**Comment by grzegorz-gutowski** [comment]
This seems like a reasonable behavior. I'll check if it's possible and try to design an appropriate icon.

**Comment by grzegorz-gutowski** [comment]
"Paused" icon is available in the newest version
