### ISSUE TITLE
SSO always opened in Firefox

### ISSUE THREAD

**Issue by Bassadin** [OpenVPN/openvpn3-indicator#9]
Hey! Love the project. :)

My main browser is chrome and it is where I got my password manager, etc. running. However, when trying to connect to out VPN with the indicator, the SSO page is always opened with Firefox and I found no way to configure anything else. I'm running EndeavorOS with KDE Plasma 6 and have Chrome configured as my default browser there.

**Comment by Bassadin** [comment]
That command actually returns `google-chrome.desktop` for me :)

**Comment by dsommers** [comment]
@Bassadin What does this little Python snippet give you?
```python3
import webbrowser
b = webbrowser.get()
print(b.name)
```

**Comment by Bassadin** [comment]
@dsommers that one actually prints out `firefox` :D

**Comment by dsommers** [comment]
@Bassadin Okay, that's the difference then .... as on my system (RHEL-8), that snippet returns `xdg-open`; which should use whatever `xdg-settings`.  The `webbrowser` Python module is provided by the Python packages, so I dunno what EndeavourOS has done so it returns `firefox`.

**Comment by MartinLoeper** [comment]
> If the environment variable BROWSER exists, it is interpreted as the [os.pathsep](https://docs.python.org/3/library/os.html#os.pathsep)-separated list of browsers to try ahead of the platform defaults.
> 
> https://docs.python.org/3/library/webbrowser.html

So make sure to set your `BROWSER` env var accordingly as it takes precedence. ;)

**Comment by Bassadin** [comment]
That was it indeed! To add to it, my solution was to just set the BROWSER env var to undefined to that xdg-open takes over :)
